<?php

namespace App\Services\Docs\Support;

class MarkdownBuilder
{
    /**
     * The auto-generated banner every doc file starts with.
     */
    public static function fileBanner(string $sourceNote): string
    {
        return "<!-- Auto-generated by `php artisan docs:generate`. Do not hand-edit — see {$sourceNote} instead. -->\n";
    }

    public static function heading(string $text, int $level = 1): string
    {
        return str_repeat('#', $level).' '.$text."\n";
    }

    /**
     * @param  list<string>  $headers
     * @param  list<list<string>>  $rows
     */
    public static function table(array $headers, array $rows): string
    {
        if ($rows === []) {
            return '';
        }

        $lines = [];
        $lines[] = '| '.implode(' | ', $headers).' |';
        $lines[] = '|'.str_repeat('---|', count($headers));

        foreach ($rows as $row) {
            $escaped = array_map(fn ($cell) => str_replace("\n", '<br>', (string) $cell), $row);
            $lines[] = '| '.implode(' | ', $escaped).' |';
        }

        return implode("\n", $lines)."\n";
    }

    public static function codeBlock(string $content, string $language = ''): string
    {
        return "```{$language}\n".rtrim($content)."\n```\n";
    }

    /**
     * @param  list<string>  $items
     */
    public static function bullets(array $items): string
    {
        return implode("\n", array_map(fn ($item) => "- {$item}", $items))."\n";
    }

    public static function note(string $text): string
    {
        return "> {$text}\n";
    }
}
